name: success
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.16
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
    - absl-py==2.1.0
    - accelerate==1.12.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.1
    - aiosignal==1.4.0
    - albucore==0.0.24
    - albumentations==2.0.8
    - annotated-types==0.7.0
    - astropy==6.1.7
    - astropy-iers-data==0.2025.3.10.0.29.26
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - attrs==25.4.0
    - bitsandbytes==0.48.2
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - contourpy==1.3.1
    - cycler==0.12.1
    - decord==0.6.0
    - einops==0.8.1
    - ema-pytorch==0.7.7
    - filelock==3.17.0
    - flatbuffers==25.2.10
    - fonttools==4.55.5
    - frozenlist==1.8.0
    - fsspec==2024.12.0
    - ftfy==6.3.1
    - gast==0.6.0
    - google-pasta==0.2.0
    - grpcio==1.70.0
    - h5py==3.13.0
    - huggingface-hub==0.30.2
    - idna==3.10
    - imageio==2.37.0
    - importlib-resources==6.5.2
    - iopath==0.1.10
    - jinja2==3.1.5
    - joblib==1.5.2
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - keras==3.8.0
    - kiwisolver==1.4.8
    - lazy-loader==0.4
    - libclang==18.1.1
    - lightning-utilities==0.15.2
    - llvmlite==0.44.0
    - mamba-ssm==2.2.4
    - markdown==3.7
    - markdown-it-py==3.0.0
    - markupsafe==3.0.2
    - matplotlib==3.10.0
    - mdurl==0.1.2
    - medpy==0.5.2
    - ml-collections==1.0.0
    - ml-dtypes==0.5.1
    - monai==1.4.0
    - mpmath==1.3.0
    - multidict==6.7.0
    - namex==0.0.8
    - networkx==3.4.2
    - nibabel==5.3.2
    - ninja==1.11.1.4
    - numba==0.61.0
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.1.105
    - opencv-python==4.11.0.86
    - opencv-python-headless==4.12.0.88
    - ops==2.19.4
    - opt-einsum==3.4.0
    - optree==0.14.1
    - packaging==24.2
    - pandas==2.3.3
    - pillow==11.1.0
    - portalocker==3.2.0
    - propcache==0.4.1
    - protobuf==5.29.3
    - psutil==7.1.3
    - ptflops==0.7.4
    - pycocotools==2.0.10
    - pydantic==2.12.3
    - pydantic-core==2.41.4
    - pyerfa==2.0.1.5
    - pygments==2.19.1
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - pytorch-lightning==2.5.5
    - pytz==2025.2
    - pywavelet==0.2.5
    - pywavelets==1.8.0
    - pyyaml==6.0.2
    - regex==2024.11.6
    - requests==2.32.3
    - rich==13.9.4
    - rocket-fft==0.2.5
    - safetensors==0.5.2
    - scikit-image==0.25.0
    - scikit-learn==1.7.1
    - scipy==1.15.1
    - sentencepiece==0.2.1
    - simpleitk==2.4.1
    - simsimd==6.5.3
    - six==1.17.0
    - stringzilla==4.2.1
    - sympy==1.13.1
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - tensorflow==2.19.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==2.5.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.6.0
    - tifffile==2025.1.10
    - timm==1.0.14
    - tokenizers==0.13.3
    - torch==2.4.1
    - torchaudio==2.4.1
    - torchmetrics==1.8.2
    - torchsummary==1.5.1
    - torchvision==0.19.1
    - tornado==6.4.2
    - tqdm==4.67.1
    - transformers==4.30.0
    - triton==3.0.0
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.3.0
    - visdom==0.2.4
    - wcwidth==0.2.14
    - websocket-client==1.8.0
    - werkzeug==3.1.3
    - wrapt==1.17.2
    - yarl==1.22.0
prefix: /home/minbo/anaconda3/envs/success
